# Generated by Django 4.1.3 on 2023-03-13 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_alter_user_options_user_username_original_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feed',
            name='unique name and owner bond',
        ),
        migrations.AlterField(
            model_name='data',
            name='date_created',
            field=models.DateTimeField(default='2023-03-13 17:55:42+00:00'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(error_messages={'unique_name_owner': 'Already exists'}, max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_.]+$', 'Feeds name contains invalid character.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username_original',
            field=models.CharField(error_messages={'unique': 'User with this username already exists.'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_.]+$', 'Username contains invalid character.')]),
        ),
        migrations.AddConstraint(
            model_name='feed',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_name_owner', violation_error_message='Exists'),
        ),
    ]
